apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 5
>>>>>>> 6711c72a566a9343bebd132ebd9835884706292c
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
